# Assignment instruction

In this part of the assignment, you are asked to answer questions about basics of python and NumPy. Answer all questions. This assignment comprises 40 percent of the assignment grade.


In [1]:
import numpy as np

# Python introduction (15 points)

Split the following string by word and create a list

In [3]:
string = "A driverless truck is ready to start earning a living"

In [4]:
string.split()

['A',
 'driverless',
 'truck',
 'is',
 'ready',
 'to',
 'start',
 'earning',
 'a',
 'living']

For the python list below, run a loop where the number will be printed out when it is greater than 15. The output should look like:
```
17
18
17
18
18
18
16
17
16
```

In [5]:
list_x = [ 0,  4, 17, 15, 10, 13,  7, 15, 13, 18,  3,  8, 17,  3,  4, 18, 15,
        0, 13, 10, 18, 18,  9, 11,  7, 16,  8,  8, 17, 10,  1,  1, 13,  7,
       15, 11,  2,  0, 16, 15,  0,  4,  2,  0,  4, 15, 14,  7, 14,  1]

In [10]:
for i in list_x:
  if i > 15:
    print(i)

17
18
17
18
18
18
16
17
16


Define a funtion `inList` with following specs.

- Takes two argments:
  - `x`: a scaler
  - `l`: a list
- The function will check whether `x` exists in the list, and print out the results
  - if exists: `value is in the list`
  - if not: `value is not in the list`

For example:

```
inList(x = 3, l = [10,4,5,3])
```

Will produce

```
3 is in the list
```

In [49]:
def inList(x, l):
  if np.isscalar(x) == False:
    return("Argument x must be a scaler object")
  elif type(l) != list:
    return("Argument l must be a list object")
  elif (x in l) == True:
    return(str(x) + " is in the list")
  else:
    return(str(x) + " is not in the list")

In [50]:
inList(x = 3, l = [10,4,5,3])

'3 is in the list'

Tests for fail conditions

In [51]:
inList(x = 42, l = [10,4,5,3]) 

'42 is not in the list'

In [52]:
inList(x = 42, l = 42) 

'Argument l must be a list object'

In [53]:
inList(x = [10,4], l = [10,4,5,3]) 

'Argument x must be a scaler object'

# Numpy (25 points)

## Array construction

Construct following NumPy arrays (without using `array()` method)

- one dimensional arrays:
    1. a sequece of integers from `-5` to `7`
    2. 10 random numbers drawn from uniform distribution 
    3. a decreasing sequence of integers from `23` to `0`
- two dimensional arrays:
    1. 7 x 5 random array drawn from normal distribution
    2. 2 x 7 array of zeros
    3. 3 x 4 array of 7s, like this
      ```
      array([[7., 7., 7., 7.],
             [7., 7., 7., 7.],
             [7., 7., 7., 7.]])
      ```


### One Dimensional Arrays

In [57]:
# 1. a sequece of integers from -5 to 7
np.arange(-5, 8)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [63]:
np.random.seed(42)

In [71]:
# 2. 10 random numbers drawn from uniform distribution
np.random.rand(10)

array([0.84228477, 0.44975413, 0.39515024, 0.92665887, 0.727272  ,
       0.32654077, 0.57044397, 0.52083426, 0.96117202, 0.84453385])

In [74]:
# 3. a decreasing sequence of integers from 23 to 0
np.arange(23,-1,-1)

array([23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,
        6,  5,  4,  3,  2,  1,  0])

### Two Dimensional Arrays

In [81]:
# 1. 7 x 5 random array drawn from normal distribution
np.random.randn(35).reshape([7,5])

array([[-2.46969887,  0.48197914,  0.92645636, -0.83758139,  0.67718607],
       [ 1.87231912,  0.39637394, -0.6256163 , -0.52246148,  0.0130339 ],
       [ 0.37776959,  0.0628246 ,  0.50159637, -0.14694539,  0.18062297],
       [ 0.96481058, -1.06483115,  0.1087118 ,  0.10576365,  0.92066672],
       [-0.22672246,  0.65304831,  1.10268747, -1.84980294,  1.16863124],
       [-0.9853818 , -1.09394041, -2.87945689, -0.80317767, -0.00485694],
       [-0.38332331, -0.46252686, -1.11249735,  0.8672295 ,  0.95841384]])

In [82]:
# 2. 2 x 7 array of zeros
np.zeros(14).reshape([2,7])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [88]:
# 3. 3 x 4 array of 7s, like this
np.ones(12).reshape(3,4) + 6

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

## Array indexing and selection

### One dimension



#### From the array below, create a replicating matrix

In [90]:
arr_1d = np.arange(1, 16)

(1) `array([1, 2, 3, 4, 5, 6, 7])`

In [93]:
arr_1d[:7]

array([1, 2, 3, 4, 5, 6, 7])

(2) `array([13, 14, 15])`

In [97]:
arr_1d[12:15]

array([13, 14, 15])

#### Do the following 

1. Set the seed to `208320`
2. Construct an array with 20 random numbers from normal distribution
3. Select positive elements from the array

In [98]:
np.random.seed(208320)

In [99]:
arr_randn = np.random.randn(20)

In [105]:
arr_randn[arr_randn > 0]

array([1.10375766e+00, 2.21785369e-01, 1.75022440e+00, 1.12668158e-01,
       5.78303818e-01, 5.98302474e-03, 5.91458661e-04, 4.47029122e-01,
       4.63016024e-01])

### Two dimension


#### From the array below, crate a replicating matrix

In [107]:
arr_2d = np.arange(31, 61).reshape(5, 6)

In [108]:
# del this afterwards
arr_2d

array([[31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

(1) 
```
array([[31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48]])
```

In [110]:
arr_2d[:3,:]

array([[31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48]])

(2) 
```
array([[39, 40, 41],
       [45, 46, 47],
       [51, 52, 53]])
```

In [117]:
arr_2d[1:4:,2:5]

array([[39, 40, 41],
       [45, 46, 47],
       [51, 52, 53]])

(3)
```
array([[43, 47],
      [55, 59]])
```

In [121]:
arr_2d[[2,4],:][:,[0,4]]

array([[43, 47],
       [55, 59]])

## Array operations

For the two dimensional array below, carry out the following operations

In [122]:
arr_op = np.array([[63, 14, 95, 12, 37, 97, 51],
                  [29,  4, 69, 13, 74, 74, 32],
                  [14, 63, 83, 52, 16, 86, 78],
                  [75, 87,  2,  8, 83,  8, 32],
                  [99,  1, 66, 12, 36, 18, 76],
                  [45, 81, 23, 54, 38, 26, 30],
                  [67, 58, 79, 31, 52, 19, 76],
                  [82, 28, 34, 66, 67, 45, 32]])

(1) calculate the sum of the entire array

In [124]:
np.sum(arr_op)

2692

(2) calculate the mean of each row

In [131]:
arr_op.mean(axis = 1)

array([52.71428571, 42.14285714, 56.        , 42.14285714, 44.        ,
       42.42857143, 54.57142857, 50.57142857])

(3) calculate the standard deviaiton of each column

In [132]:
arr_op.std(axis = 0)

array([26.42323788, 32.30325061, 30.69176396, 21.70829335, 21.27755566,
       32.28752662, 20.92508961])